### ISSUE TITLE
Encoding::ConverterNotFoundError: code converter not found (UTF-8 to utf8)

### ISSUE THREAD

**Issue by orr721** [molybdenum-99/mormor#1]
hi,

upon running the example I get an error message:

```
irb(main):001:0> require 'mormor'
=> true
irb(main):002:0> sk = MorMor::Dictionary.new('slovak')
=> #<MorMor::Dictionary slovak>
irb(main):003:0> sk.lookup('drevo')
Encoding::ConverterNotFoundError: code converter not found (UTF-8 to utf8)
	from /Library/Ruby/Gems/2.3.0/gems/mormor-0.0.1/lib/mormor/dictionary.rb:56:in `encode'
	from /Library/Ruby/Gems/2.3.0/gems/mormor-0.0.1/lib/mormor/dictionary.rb:56:in `lookup'
	from (irb):3
	from /usr/bin/irb:11:in `<main>'
```

my environtment is: macOS 10.13.6 (HighSierra), ruby 2.3.7p456 (macOS preinstalled)

any clues? thanks for your work.

**Comment by zverok** [comment]
Slovak dictionary uses `fsa.dict.encoding=utf8` flag and Ruby can't recognize `utf8` as a valid encoding.
I'll try to think about more robust way of encoding detection, but for now, you can just change this line of `slovak.info` with any text editor into `fsa.dict.encoding=utf-8`. I checked, it works after that:
```ruby
sk = MorMor::Dictionary.new('test/slovak')
sk.lookup('drevo')
# => [#<struct MorMor::Dictionary::Word stem="drevo", tags="SSns1">, #<struct MorMor::Dictionary::Word stem="drevo", tags="SSns4">, #<struct MorMor::Dictionary::Word stem="drevo", tags="SSns5">] 
```

**Comment by orr721** [comment]
yep, it works now, thank you..

**Comment by glaszig** [comment]
the dictionary instance can also be patched:

```rb
dict = MorMor::Dictionary.new(path)
dict.instance_variable_set :@encoding, Encoding::UTF_8
```

**Comment by zverok** [comment]
Actually, it seems that `utf8` is the common way for Morfologik dictionaries to declare this encoding. I just released v.0.0.2, which handles this gracefully.
